events:
  - name: SliceDeletionFailed
    reason: SliceDeletionFailed
    action: SliceDeletion
    type: Warning
    reportingController: controller
    message: Slice deletion failed - please ask admin to check the slice configuration on the worker cluster. <link to tech doc event-list>
  - name: LicenseSecretNotFound
    reason: LicenseNotFound
    action: LicenseValidation
    type: Warning
    reportingController: controller
    message: Secret with license config not found. Please ensure to create license secret if this is airgapped cluster.
  - name: MachineFileNotFound
    reason: MachineFileNotFound
    action: FetchMachineFileFromSecret
    type: Warning
    reportingController: controller
    message: Machine File not present in license secret.Please contact kubeslice support team.
  - name: MachineFileInvalid
    reason: MachineFileInvalid
    action: VerifyMachineFile
    type: Warning
    reportingController: controller
    message: Machine File is invalid in license secret.Please contact kubeslice support team.
  - name: LicenseKeyInvalid
    reason: LicenseKeyInvalid
    action: DecryptMachineFile
    type: Warning
    reportingController: controller
    message: License Key is invalid in license secret.Please contact kubeslice support team.
  - name: LicenseExpired
    reason: LicenseExpired
    action: ValidateLicense
    type: Warning
    reportingController: controller
    message: License Expired , please contact kubeslice support team to get it renewed!
  - name: LicenseExpiredGracePeriodOn
    reason: LicenseExpiredGracePeriodOn
    action: ValidateLicense
    type: Warning
    reportingController: controller
    message: License Expired , grace period is on ,please contact kubeslice support team to get it renewed!
  - name: MachineFingerPrintErr
    reason: MachineFingerPrintErr
    action: GetMachineFingerPrint
    type: Warning
    reportingController: kubeslice-controller
    message: Unable to fetch MachineFingerPrint.Please look at the kubeslice-controller logs for more details.
  - name: GotMachineFingerPrint
    reason: GotMachineFingerPrint
    action: GetMachineFingerPrint
    type: Normal
    reportingController: kubeslice-controller
    message: Got MachineFingerPrint successfully
  - name: ConfigMapErr
    reason: ConfigMapErr
    action: GetConfigMap
    type: Warning
    reportingController: kubeslice-controller
    message: Unable to validate license keys from configmap. please contact kubeslice support team
  - name: GotConfigMap
    reason: GotConfigMap
    action: GetConfigMap
    type: Normal
    reportingController: kubeslice-controller
    message: Got ConfigMap and kubeslice-license public keys successfully.