name: build-test-kubeslice-monitoring
on:
  pull_request:
    branches:
    - 'master'
    - 'release-*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2
        with:
          file: test.Dockerfile
          tags: test-image:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: make test
